spring.application.name=AmlTmServer

spring.datasource.url=jdbc:postgresql://localhost:5432/{dbname}
spring.datasource.username=postgres
spring.datasource.password={password}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.open-in-view=false