package org.tss.tm.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.tss.tm.entity.system.SystemAdmin;
import org.tss.tm.repository.SystemAdminRepo;

@Component
@RequiredArgsConstructor
@Slf4j
public class DatabaseSeeder implements CommandLineRunner {

    private final SystemAdminRepo systemAdminRepo;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        seedSystemAdmin();
    }

    private void seedSystemAdmin() {
        String adminEmail = "admin@tss.org";
        if (systemAdminRepo.findByEmail(adminEmail).isEmpty()) {
            log.info("Seeding default system admin...");
            SystemAdmin admin = SystemAdmin.builder()
                    .firstName("System")
                    .lastName("Admin")
                    .phoneNumber("+919876543210")
                    .email(adminEmail)
                    .passwordHash(passwordEncoder.encode("admin123"))
                    .isActive(true)
                    .build();
            
            // The systemAdminCode will be auto-generated by the DB trigger if left null,
            // but we can also set a default one if needed.
            admin.setSystemAdminCode("SADM-000001");
            
            systemAdminRepo.save(admin);
            log.info("Default system admin created successfully (Email: {}, Password: admin123).", adminEmail);
        } else {
            log.info("System admin with email {} already exists. Skipping seeding.", adminEmail);
        }
    }
}
